# Generated by Django 5.0.1 on 2024-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "rid",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("blogurl", models.URLField()),
                ("contact", models.IntegerField()),
                ("country", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("password", models.CharField(max_length=120)),
                ("collegename", models.CharField(max_length=120)),
                ("branch", models.CharField(max_length=120)),
                ("stream", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("proof", models.FileField(upload_to="proof/")),
                ("discribe", models.CharField(max_length=200)),
            ],
        ),
    ]
