# Generated by Django 5.0.1 on 2024-03-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=5000)),
                ("image", models.ImageField(upload_to="proof/")),
            ],
        ),
    ]
