# Generated by Django 5.0.1 on 2024-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0002_bookitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=1000)),
                ("date", models.DateField()),
                ("image", models.ImageField(upload_to="proof/")),
            ],
        ),
    ]
