# Generated by Django 5.0.1 on 2024-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0003_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="author",
            field=models.CharField(default="Raghuram", max_length=50),
        ),
    ]
