# Generated by Django 5.0.1 on 2024-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0005_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="mainblog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Author", models.CharField(max_length=50)),
                ("Title", models.CharField(max_length=120)),
                ("link", models.URLField(blank=True)),
                ("description", models.CharField(max_length=5000)),
                ("date", models.DateField()),
            ],
        ),
    ]
