# Generated by Django 5.0.1 on 2024-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0006_mainblog"),
    ]

    operations = [
        migrations.CreateModel(
            name="uploadblog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("authorname", models.CharField(max_length=50)),
                ("link", models.URLField(blank=True)),
                ("description", models.CharField(max_length=5000)),
                ("stream", models.CharField(max_length=100)),
            ],
        ),
    ]
