# Generated by Django 5.0.1 on 2024-04-02 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0007_uploadblog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadblog",
            old_name="authorname",
            new_name="name",
        ),
    ]
