# Generated by Django 5.0.1 on 2024-04-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0008_rename_authorname_uploadblog_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadblog",
            old_name="name",
            new_name="authorname",
        ),
        migrations.AddField(
            model_name="uploadblog",
            name="email",
            field=models.EmailField(default="demo@gmail.com", max_length=254),
        ),
    ]
