# Generated by Django 5.0.1 on 2024-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0009_rename_name_uploadblog_authorname_uploadblog_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="email",
            field=models.EmailField(default="demo@gmail.com", max_length=254),
        ),
    ]
