# Generated by Django 5.0.1 on 2024-04-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0010_book_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="proof/"
            ),
        ),
    ]
