# Generated by Django 5.0.1 on 2024-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0013_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(upload_to="proof/"),
        ),
    ]
