# Generated by Django 5.0.1 on 2024-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0014_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="email",
            field=models.EmailField(default="hari@gmail.com.com", max_length=254),
        ),
    ]
