# Generated by Django 5.0.1 on 2024-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0015_alter_book_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="email",
            field=models.EmailField(default="hari@gmail.com.com", max_length=254),
        ),
    ]
