# Generated by Django 5.0.1 on 2024-04-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0016_blogs_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="email",
            field=models.EmailField(default="hari@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(upload_to="books/"),
        ),
    ]
