# Generated by Django 5.0.1 on 2024-04-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0017_alter_blogs_email_alter_blogs_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(upload_to="proof/"),
        ),
    ]
