# Generated by Django 5.0.1 on 2024-04-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0019_alter_blogs_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.FileField(default="proof/django.jpeg", upload_to="proof/"),
        ),
    ]
