# Generated by Django 5.0.1 on 2024-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0020_alter_blogs_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.FileField(
                default="images/default_image.jpg", upload_to="images/"
            ),
        ),
    ]
