# Generated by Django 5.0.1 on 2024-04-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0023_alter_bookitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookitem",
            name="image",
            field=models.FileField(
                default="proof/default_image.jpeg", upload_to="proof/"
            ),
        ),
    ]
