# Generated by Django 5.0.1 on 2024-04-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0026_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="demo@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(default=9867534210),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.IntegerField(),
        ),
    ]
